spring:
  profiles:
    active: dev
  application:
    name: camel_rest

camel:
  springboot:
    main-run-controller: true


myconfig:
  testDirectory: file:temp/testarea
  camelContainer:
    jobParamCopyFile:
      srcDirectory: file:temp/testarea/srcDir
      dstDirectory: file:temp/testarea/dstDir

