spring:
  profiles:
    active: dev
  application:
    name: camel_rest

myconfig:
  testDirectory: file:~/temp/testarea
  camel:
    copyFile:
      srcDirectory: file:~/temp/testarea/srcDir
      dstDirectory: file:~/temp/testarea/dstDir