server:
  port: ${API_PORT:8980}
  servlet:
    context-path: "/camel_rest/api"
  # For include message error to http response!!!
  error:
    include-message: always

logging:
  level:
    root: info
  file:
    path: log/

management:
  health:
    probes:
      enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
      enabled: true
    caches:
      enabled: true
    info:
      enabled: true
      show-details: always
    beans:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/shop_kotlin/api/actuator"
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  server:
    port: 8988


