spring:
  profiles:
    active: dev
  application:
    name: camel_rest

camel:
  springboot:
    main-run-controller: true


myconfig:
  testDirectory: file:/tmp/testarea
  camelContainer:
    jobParamCopyFile:
      srcDirectory: ${myconfig.testDirectory}/srcDir
      dstDirectory: ${myconfig.testDirectory}/dstDir

